language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  global:
    secure: cOnxkw37k6yRN15iyjTsqcf8dHlcqdRuQ9waY2olv0Zv01KFgltr45qj504nS609K2nFPVRdOrbkJAMOVesjVulDKwJGwj4njgfL0DNQCeGoQigjoKIRZ1C+Mx14F54cM6n2BcTuLw0OjcAHA5o11Y8haky1d8NJIwBPfj8p/kY4s9wBeTyw/+g8QF3cBHYAMUPkGBRGfZNLqO3J4XRpbwo/NkGMhYI3FhHRUR10jtCZx8y2Uy2hMzLmsQHYHLPt4+o7xFDLujDm6OKZaQP/RXFvAIBQ0XqCBE/TMeyIK1knTj0DwLVeXKaVrTIc376/9f+KhZsv0XCT1Izamk16xmKovSz2FGBz7VDFq9YoF0qQlZ2cQMjL7/42Tas3rUymQmJECALqX34Nd8OvNDcSPuThe475zYrk7ZRhpUjRkfmV1XCkPLUmssVE5NLwqCXoSRdjXwsDHr1vdcqnBicicdp1AW/KqSij/X2u0W3DadJORymPHxq4b9SCtGxzCjwYXHuLX/2sB9zqYBEMin9P43kKr2I/XIXWpwc7UvHQHaIkSGv3Rcajx8L/SqaUMLN/A5BC+uJnFsxMZMWGH/ZG4PmDTd7Xbr5egpjivZC6lrPDYsWyFW6HfWT3sOJz0sMLzllbRS3mw0s55zD1NCLC+Si2Y4ywD2gAWQZcVsp5exA=
before_install:
- openssl aes-256-cbc -K $encrypted_ce57a6517705_key -iv $encrypted_ce57a6517705_iv
  -in src/blynk_setup.tar.gz.enc -out src/blynk_setup.tar.gz -d
- tar -xzf src/blynk_setup.tar.gz
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: eqMMDtMLTFsAkNwcjEUAb0vTH6BI3tVj7wOHNrNqAFmoNxfXQ7ZoruA/B4AP1KoT/AI/n5+PuIpptMzvRVaaYI79WlpImmp3uG3vjq/o2TTIO3R3+m4iKnnMm/H3K6dpef8qqCW/s8tAyX0RGMCpcSKX108q9AcBFnkLtH3uh343b+KcHhs6fnuHIc2gZPHp3JR8YqBKgGwQGfGl8JMQXQhfC/OdQ4OiwWQVjCT8a8L7vcFD3Jq7XKcQL8TgaIcZLOKH+wUYzGVxfNeI++9xFqyW2GWdDNUzjQmYBfB/A6Eyzl4iYbbGRPEnDEtE+XNoA27jrvKaRvhKlutTU96EyoPZVJdw4WDYp53L/SnyR7VkDFEbBcddMDJ2u+LgOsk+iXXbRZeT6iY3V0uSogyK+pvrbUFm7ynlzXdwhLqSFHIjpUgeNeLosH3ra3dcnQ04wwBOdVYxRMRnykWQ3CJpQqh4GQxzq7OPTOgSZKmWckaTa2VtJtA+POmUyrzlUVR9scz2jpG7tbshAL0EodIvlcb3kkl9p74JQ8ngP8z6+TxXJ2Xa33/cmeVb0Yo5h1RBWoqHdh67+Jb7y58DNCFVh8zRrz+UmaF3qIJiddk4y0u1Sx7fUTwpNG9lVO1Ch3y6S4MMErg8cH7Hne9C5O0IFHCbvjeAiDMApk1MOzyMj/I=
  file: ".pioenvs/esp12e/firmware.bin"
  skip_cleanup: true
  on:
    repo: gearbox/Air
    all_branches: true
    tags: true
